---
spring:
  application:
    name: terrain_petanque
  datasource:
    url: jdbc:mariadb://localhost:3306/terrain_petanque
    username: terrain_petanque
    password: password-group1
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
      hibernate:
          ddl-auto: validate
jwt:
    secret: xhuijuygfcdxcgbjdfghjpkoihygftyhujiygtfdfghjihfxdfghjkhgfxfchjnkhgcfxdfcvbjnbgcxsdwxfchbhgfscgvbnjahgvfcsgvbanjhfcsxfcahbfcsxdfachbjsgfdrftahbsvcxadftgyhbxd
    duration: 7200000
server:
  port: 8081
